# (PART\*) Ten Reasons to Learn R {.unnumbered}

# R is free and open source

::: {.goals}
-   What is free and open source software (FOSS)?
-   Is free and open source software reliable?
:::

A great reason for choosing R over commercial software packages is that it is is **free
and open source software (FOSS)**, and the license under which R is published guarantees
that it will stay like that forever. But what does that mean?

#### Free {.unnumbered}

This means that nobody owns exclusive rights to R, and anyone can obtain a copy of R for
free and modify it however they like. It means that you can use R everywhere, and you can
use any version of it at any time. No license fees or purchasing costs means also means
less bureaucracy! This is great for collaboration, sharing, and reproducibility.

Finally, being free means that you can simply give R a spin and see if it's for you --- no
strings attached!

#### Open Source {.unnumbered}

This means that nobody really controls the development of R. If any functionality is
missing, R users can create it themselves, and --- as we will see later --- they do! There
are tens of thousands of extensions (*packages*) for R that were created by the R
community and are free for everyone to use.

## Is R reliable?

Make no mistake: Free and open source does not mean unprofessional! The R project is very
stable, and there is a core team of computer scientists and statisticians guiding its
development. While a lot of the improvements to R are contributed by volunteers, the
project does receive financial support

-   **directly** from companies such as [RStudio](https://www.rstudio.com/) and
    [rOpenSci](https://ropensci.org/), who employ developers to improve R, and

-   **indirectly** through people who contribute to the R project as part of their jobs
    (e.g., research software engineers, statisticians, data scientists).

There are also peer-reviewed journals such as the [*Journal of Statistical
Software*](https://www.jstatsoft.org/index) and the R project's own [*R
Journal*](https://journal.r-project.org/archive/2020-2/), which academics can use to get
credit for working on R-related things. It's also common to see papers in other journals
introducing statistical methods along with an implementation in R.

::: {.exercise}
Can you think of any other free and open source software you are using --- perhaps even on
a daily basis?

::: {.answer}
-   Firefox is a FOSS project. Google's Chrome browser itself is not, but it is built on
    top of a FOSS project, called Chromium.

-   Linux is an operating system like Windows or MacOS, that powers many servers on the
    internet. Even if you are not using Linux yourself, you have probably communicated
    with a Linux computer today.

-   Android is an open source operating system. Unless you are using an iPhone, you are
    probably using it.
:::
:::
